version: '3.7'

services:
  mongo:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      command: --config /etc/mongo/mongod.conf
      volumes:
        - ./data/mongo:/data/db
        - ./config/mongod.conf:/etc/mongo/mongod.conf
      ports:
        - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"