---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Hypervisor/Container:
    - Proxmox:
        icon: proxmox.svg
        href: https://x.x.x.x:8006
        description: pve1
        widget:
            type: proxmox
            url: "https://x.x.x.x:8006"
            username:  api@pam!homepage
            password:  $PASS
            node: proxmox
    - Proxmox:
        icon: proxmox.svg
        href: https://x.x.x.x:8006
        description: pve2
        widget:
            type: proxmox
            url: "https://x.x.x.x:8006"
            username:  api@pam!homepage
            password:  $PASS
            node: pve-2
    - Portainer:
        icon: portainer.svg
        href: https://10.10.10.173:9443/
        description: docker
        widget:
            type: portainer
            url: "https://10.10.10.173:9443"
            env: 2
            key: $KEY
- Status:
    - Router:
        icon: "mikrotik.svg"
        description: internal router
        widget: 
            type: mikrotik
            url: "http://x.x.x.x:8728"
            username: admin
            password: $PASS
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "http://uptime.jegyrendszer.local/"
        description: internal
        widget:
            type: uptimekuma
            url: "http://uptime.jegyrendszer.local"
            slug: default
    - Grafana:
        icon: grafana.svg
        href: "http://grafana.jegyrendszer.local"
        description: internal
        widget:
            type: grafana
            url: "http://grafana.jegyrendszer.local"
            username: admin
            password: $PASS
    - Traefik: 
        icon: "traefik.svg"
        description: utilites proxy
        widget:
            type: traefik
            url: "http://x.x.x.x:8080"
    - Speed:
        icon: librespeed.svg
        href: "x.x.x.x:y"
        description: internal
        widget:
            type: speedtest
            url: "http://x.x.x.x"
- Services:
    - Nextcloud:
        icon: "nextcloud.svg"
        href: ""
        description: in deployment...
        widget:
            type: nextcloud
            url: ""
            key: ""
    - Prometheus:
        icon: "prometheus.svg"
        description: internal prometheus
        widget:
            type: prometheus
            url: http://x.x.x.x:80
    - Shlink:
        icon: "shlink.svg"
        href: "http://x.x.x.x:8888/"
    - Minecraft server:
        icon: "minecraft.svg"
        description: papermc
        widget:
            type: minecraft
            url: udp://x.x.x.x:25565
- Other:
    - Jegyrendszer:
        href: https://jegy.bnbdevelopment.cloud
    - Jegyrendszer admin:
        href: https://jegy.bnbdevelopment.cloud/admin
