name: "Build Android app"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # macos-latest
    defaults:
      run:
        working-directory: ./app # set accordingly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenJDK 17 (JDK & JRE)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk openjdk-17-jre
          java -version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn' # npm | yarn | pnpm

      - name: Install packages
        # yarn install | npm install | pnpm install
        run: |
             npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # for AAB file use bundleRelease
      - name: Build application
        run: |
             unset _JAVA_OPTIONS
             unset JAVA_TOOL_OPTIONS
             cd android
             ./gradlew clean
             ./gradlew assembleRelease

      # for AAB file: android/app/build/outputs/bundle/release/app-release.aab
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 3

      - name: Upload APK to server
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          scp -o StrictHostKeyChecking=no app/build/outputs/apk/release/app-release.apk $USERNAME@$HOST:/var/www/html/latest.apk
