apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 1
      steps:
      - setWeight: 10
      - pause:
          duration: 1h 
      - setWeight: 20
