logLevel: info
harborAdminPassword: Harbor12345
expose:
  type: ingress
  ingress:
    hosts:
      core: reg.bnbdevelopment.cloud
  tls:
    enabled: true
    # secretName: harbor-tls
    # notary:
    #   enabled: true
    #   secretName: harbor-notary-tls
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: longhorn
      accessMode: ReadWriteMany
    chartmuseum:
      storageClass: longhorn
      accessMode: ReadWriteMany
    jobservice:
      storageClass: longhorn
      accessMode: ReadWriteMany
metrics:
  enabled: true
  serviceMonitor:
    enabled: true