architecture: replicaset
replicaCount: 2
auth:
  enabled: true
  rootUser: root
  rootPassword: "root"
image:
  tag: 4.2.21-debian-10-r8
metrics:
  enabled: true
readinessProbe:
  timeoutSeconds: 5
initdbScripts:
  my_init_script.js: |
    db.createUser({
      user: "admin",
      pwd: "admin",
      roles: [
        { role: "readWrite", db: "admin" },
        { role: "dbAdmin", db: "admin" },
        { role: "userAdmin", db: "admin" },
        { role: "clusterAdmin", db: "admin" },
        { role: "root", db: "admin" }
      ]
    });
arbiter:
  enabled: false