architecture: replicaset # `replicaset` or `standalone`
### ONLY FOR REPLICASET ###
# replicaCount: 2
auth:
  enabled: true
  rootUser: root
  rootPassword: root
metrics:
  enabled: true
  collector:
    all: true
  serviceMonitor: # prom-operator
    enabled: true
    namespace: monitoring # namespace of prom operator
  prometheusRule: # prom-operator
    enabled: false
    namespace: monitoring # namespace of prom operator
readinessProbe:
  timeoutSeconds: 5
initdbScripts:
  my_init_script.js: |
    db.createUser({
      user: "admin",
      pwd: "admin",
      roles: [
        { role: "readWrite", db: "admin" },
        { role: "dbAdmin", db: "admin" },
        { role: "userAdmin", db: "admin" },
        { role: "clusterAdmin", db: "admin" },
        { role: "root", db: "admin" }
      ]
    });
arbiter:
  enabled: false