version: '3.7'
services:
  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=192.168.50.160
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      # - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    ports:
      - 51820:51820
    volumes:
      - ./data/wg:/config
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
    restart: unless-stopped
    networks:
      wireguard-internal:
        ipv4_address: "10.0.0.5"


networks:
  wireguard-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"