apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-deployment
  labels:
    app: anotherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anotherapp
  template:
    metadata:
      labels:
        app: anotherapp
    spec:
      containers:
      - name: anotherapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
