version: '3.7'
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as:2.9.0-5c5bd120-Ubuntu18-ls124
    cap_add:
      - NET_ADMIN
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    volumes:
      - ./data/as:/config
    ports:
    - 943:943
    - 9443:9443
    - 1194:1194/udp
    restart: unless-stopped
    networks:
      default:
      openvpn-internal:
        ipv4_address: "10.0.0.5"

networks:
  openvpn-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
