apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: shipping-allow-eks
spec:
  destination:
    name: shippingservice
  sources:
   - name: frontendservice
     action: allow
     peer: eks