apiVersion: v1
kind: Service
metadata:
  name: mongo-lb
  namespace: service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo-release
    app.kubernetes.io/name: mongodb
  ports:
  - port: 27017
    targetPort: 27017
