---
- name: Update and upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes
    pkg:
      - vim
      - qemu-guest-agent

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl