groups:
- name: UPS_ALERTS
  rules:
  - alert: UPS_status_OB
    expr: nut_ups_status{status="OB"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: UPS ON BATTERY
      description: "UPS is running on battery power"
  - alert: UPS_status_LB
    expr: nut_ups_status{status="LB"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: UPS LOW BATTERY
      description: "UPS battery is running out"
  - alert: UPS_status_OFF
    expr: nut_ups_status{status="OFF"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: UPS POWER IS OFF
      description: "UPS is off"
  - alert: UPS_charge_50
    expr: nut_battery_charge * 100 < 50
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Battery Charge Level Low"
      description: "The UPS battery charge level is below 25%. Current charge: {{ $value }}%."
  - alert: UPS_charge_25
    expr: nut_battery_charge * 100 < 25
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Battery Charge Level Low"
      description: "The UPS battery charge level is below 25%. Current charge: {{ $value }}%."
  - alert: LowBatteryRuntime
    expr: nut_battery_runtime_seconds < 300
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Low Battery Runtime"
      description: "The UPS battery runtime is less than 5 minutes. Current runtime: {{ $value }} seconds."
  - alert: InputVoltageOutOfRange
    expr: nut_input_voltage_volts < 100 or nut_input_voltage_volts > 240 
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Input Voltage Out of Range"
      description: "The UPS input voltage is out of range. Current voltage: {{ $value }}V."