global:
  # peering:
  #   enabled: true
  tls:
    enabled: true
  metrics:
    enabled: true
    enableAgentMetrics: true

server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "TRACE",
      "telemetry": {
        "disable_hostname": true
      }
    }

client:
  extraConfig: |
    {
      "log_level": "TRACE",
      "telemetry": {
        "disable_hostname": true
      }
    }

connectInject:
  enabled: true
  default: false

# meshGateway:
#   enabled: true
#   replicas: 1

controller:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer