# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nginx-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   csi:
#     driver: driver.longhorn.io
#     fsType: ext4
#     volumeAttributes:
#       numberOfReplicas: '3'
#       staleReplicaTimeout: '30'
#     volumeHandle: pvc-0eb2096e-f46e-431b-bfdc-60e4b8150d06
#   storageClassName: longhorn
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nginx-volume-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: longhorn
#   volumeName: nginx-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    name: nginx-test
spec:
  volumes:
  - name: nginx-volume
    persistentVolumeClaim:
      claimName: nginx-volume-claim
  - name: backing-volume  
    persistentVolumeClaim:
      claimName: uptime-kuma-pvc
  containers:
  - name: nginx-test
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: nginx-volume
      mountPath: /share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi