version: "3.7"
services:
  tailscale:
      image: tailscale/tailscale:v1.74.1
      container_name: "tailscale"
      hostname: "host"
      environment:
        - TS_AUTHKEY=$AUTH_KEY
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_ROUTES=10.10.10.0/24
      volumes:
        - ./tailscale/state:/var/lib/tailscale
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
        - sys_module
      restart: unless-stopped
      ### UNCOMMENT IF DEDICATED NETWORK
      # networks:
      #   server_stack:
      #     ipv4_address: 10.0.0.1
      ###
### UNCOMMENT IF DEDICATED NETWORK
# networks:
#   server_stack:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: "10.0.0.0/24"
###