version: "3.7"

services:
  runner:
    image: tcardonne/github-runner:ubuntu-20.04
    environment:
      RUNNER_NAME: "ga-dr-1"
      RUNNER_REPOSITORY_URL: "https://github.com/YOUR/REPOISTORY"
      RUNNER_TOKEN: $RUNNER_TOKEN
    networks:
      cicd:
        ipv4_address: 172.20.0.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  cicd:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
