apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <base64-encoded-ca-cert>
    server: https://<kubernetes-api-server>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: read-only-user
  name: read-only-context
current-context: read-only-context
users:
- name: read-only-user
  user:
    client-certificate-data: <base64-encoded-user-cert>
    client-key-data: <base64-encoded-user-key>
