mode: standalone # or distributed
### IF DISTRIBUTED ###
# statefulset: 
#   replicaCount: 8
### IMAGE DEBUG ###
# image:
#   debug: true
auth:
  rootUser: admin
  rootPassword: adminadmin # min 8 characters
defaultBuckets: "" # , separated
tls:
  enabled: false
### INGRESS ###
# ingress:
#   enabled: true
#   hostname: HOSTNAME.LOCAL
#   path: /
### API INGRESS ###
# apiIngress:
#   enabled: true
#   hostname: API.HOSTNAME.LOCAL
persistence:
  enabled: true
  storageClass: longhorn
metrics:
  serviceMonitor:
    enabled: true  # for prom-operator
    namespace: monitoring # namespace of prometheus
  # prometheusRule:
  #   enabled: true # alerting
  #   namespace: monitoring
livenessProbe:
  enabled: false
startupProbe:
  enabled: false
readinessProbe:
  enabled: false
extraEnvVars:
  - name: MINIO_LOG_LEVEL # debug log level
    value: DEBUG
  - name: MINIO_API_ROOT_ACCESS # disable root access - make sure you have an existing user with `consoleAdmin` policy
    value: off